# Generated by Django 3.0.3 on 2020-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('cfhandle', models.CharField(max_length=30, verbose_name='cfhandle')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
        ),
    ]
